# Generated by Django 3.2.6 on 2021-09-20 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210920_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('/^(?=.*\\d)(?=.*[a-zA-Z])[0-9a-zA-Z]{5,16}$/', 'only valid email is required')], verbose_name='사용자 비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{8,15}$', 'only valid email is required')], verbose_name='사용자 전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('[\\w\\.-]+@[\\w\\.-]+', 'only valid email is required')], verbose_name='사용자 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('/^[a-z]+[a-z0-9]{2,9}$/g', 'only valid email is required')], verbose_name='사용자 아이디'),
        ),
    ]
