# Generated by Django 3.2.6 on 2021-09-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
