# Generated by Django 3.2.6 on 2021-09-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='created_at',
            new_name='write_dttm',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='board',
            name='board_name',
            field=models.CharField(default='Consulting Record', max_length=32, verbose_name='게시판 종류'),
        ),
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='board',
            name='update_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
